on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: ./.github/workflows/hello-world-composite-run-steps-action@v1
      with:
        who-to-greet: 'Kuma father of Shiva'
    - run: echo random-number ${{ steps.foo.outputs.random-number }} 
      shell: bash
